export const MORAL_DECREASE_FOR_DEBT_DAY = 5;
export const MORAL_INCREASE_FOR_CONTRACT_COMPLETION = 5;
export const MORAL_DECREASE_FOR_MERCENARY_DEBT_LEAVE = 50;

export const GUILD_MERCENARY_INITIAL_MORAL = 100;
export const GUILD_MERCENARY_MORAL_MIN = 0;
export const GUILD_MERCENARY_MORAL_MAX = 100;
